### ISSUE TITLE
Missing LICENSE file in release tarball 0.12.1

### ISSUE THREAD

**Issue by stewarthaines** [sbtinstruments/asyncio-mqtt#106]
The tarball for 0.12.1 on pypi is missing the LICENSE file. The LICENSE file is present in the 0.12.0 tarball.

https://files.pythonhosted.org/packages/c1/0f/c34c727d3184c7430e547a8c6b1b60099b347c6356ff4962ecfc66313850/asyncio_mqtt-0.12.1.tar.gz

When I ran 'python setup.py sdist' with v0.12.1 branch checked out locally the tarball includes the LICENSE file. Is the tarball built in some other way?

Thanks

**Comment by frederikaalund** [comment]
Hi Stewart, thanks for opening this issue. Let me have a look. :)

> `python setup.py sdist`

That's the exact command that I run when I make a release.

I can't find the LICENSE file in the 0.12.0 or 0.11.1 tarballs:

https://files.pythonhosted.org/packages/cd/0a/d8ab9a6b069c26426fef4e7802863d6439cf684a238c4d3b16a8f62ea31f/asyncio_mqtt-0.12.0.tar.gz
https://files.pythonhosted.org/packages/0d/16/5c7ba8321f67114eab14b12d59c8cae7d6fdde7f7b994a9f321ab7b77c8e/asyncio_mqtt-0.11.1.tar.gz

I don't think that the LICENSE file was ever in the tarballs from PyPI to begin with. Note that the tarballs from GitHub includes the LICENSE file (GitHub auto-generates the tarballs from the repo). Maybe that caused the confusion?

That being said, I'd gladly accept a PR that changes `setup.py` so that it includes the LICENSE file. :+1: 

~Frederik

**Comment by stewarthaines** [comment]
Hi Frederik,

You are correct that I was confused about where I'd pulled the tarball from to find the LICENSE file. The issue is totally about getting the LICENSE file into the pypi tarball.

From what I have understood (and checked with test.pypi.org) the added setup.cfg in #107 should provide the LICENSE file in the tarball that our CI wants to check for.

Thanks!

**Comment by frederikaalund** [comment]
Closed by #107.
