### ISSUE TITLE
Should Python 3.6 support be dropped?

### ISSUE THREAD

**Issue by JonathanPlasse** [sbtinstruments/asyncio-mqtt#141]
Python 3.6 reached its end of life nearly a year ago.
So, maybe we should remove its support.

**Comment by frederikaalund** [comment]
You're right, let's move on to Python 3.7 already. 👍

The README doesn't even advertise support for 3.6. I just kept compatibility for 3.6 around because I saw no reason to break it. If, however, it makes asyncio-mqtt more maintainable then I'm all for it. 😄 I guess that there are hacks/workarounds here and there that we can remove.

Go ahead!
