### ISSUE TITLE
Executing <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:639

### ISSUE THREAD

**Issue by AndreasHeine** [sbtinstruments/asyncio-mqtt#164]
i am currently testing thruput on a project

setup:
node-red client firing 1000 msg/s -> mosquitto broker on localhost -> asyncio-mqtt client
all on the same machine (intel i7 (6c12t), 16 gig ram, ...)

i just wildcard subscribe the topics:
```python
async with AsyncExitStack() as stack:
            tasks = set()
            stack.push_async_callback(self._cancel_tasks, tasks)
            client = Client(
                protocol=ProtocolVersion.V5,
                hostname=self.config.broker,
                port=self.config.port,
                client_id=self.client_id,
                clean_start=True,
                username=self.config.user,
                password=self.config.password,
                keepalive=60,
                will=Will(
                    topic=self.config.last_will_topic,
                    payload=self.config.last_will_payload,
                    qos=1,
                    retain=True,
                    properties=create_last_will_props(self.config.enginename, 1)
                )
            )

            await stack.enter_async_context(client)

            for topic_filter in self.topics_to_subscribe:
                manager = client.filtered_messages(topic_filter)
                messages = await stack.enter_async_context(manager)
                task = create_task(self._process_messages(messages, self.recv_queue))
                tasks.add(task)

            messages = await stack.enter_async_context(client.unfiltered_messages())
            task = create_task(self._no_match_messages(messages))
            tasks.add(task)

            task = create_task(self._publish_messages(client, self.send_queue))
            tasks.add(task)

            for topic in self.topics_to_subscribe:
                await client.subscribe(topic)

            await client.publish(
                topic=self.config.last_will_topic,
                payload=self.config.online_payload,
                qos=1,
                retain=True,
                properties=create_state_props(self.config.enginename)
            )

            async def exit(*args):
                return await client.publish(
                    self.config.last_will_topic,
                    payload=self.config.offline_payload,
                    qos=1,
                    retain=True,
                    properties=create_state_props(self.config.enginename)
                )

            stack.push_async_exit(exit)

            await gather(*tasks)

    async def _process_messages(self, messages: AsyncGenerator[MQTTMessage, None], queue: Queue):
        async for message in messages:
            continue

```
literally do nothing ^^ just "continue"

after a while:
```
Executing <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:639 created at /usr/local/lib/python3.8/asyncio/selector_events.py:259> took 0.112 seconds
Executing <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:639 created at /usr/local/lib/python3.8/asyncio/selector_events.py:259> took 0.574 seconds
Executing <Handle _wait.<locals>._on_completion(<Task finishe...client.py:489>) at /usr/local/lib/python3.8/asyncio/tasks.py:518 created at /usr/local/lib/python3.8/asyncio/events.py:81> took 4.561 seconds
Executing <Handle _wait.<locals>._on_completion(<Task finishe...client.py:489>) at /usr/local/lib/python3.8/asyncio/tasks.py:518 created at /usr/local/lib/python3.8/asyncio/events.py:81> took 6.893 seconds
Executing <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:639 created at /usr/local/lib/python3.8/asyncio/selector_events.py:259> took 9.996 seconds
Executing <Handle Client._on_socket_open.<locals>.cb() at /usr/local/lib/python3.8/site-packages/asyncio_mqtt/client.py:639 created at /usr/local/lib/python3.8/asyncio/selector_events.py:259> took 12.727 seconds
```

a little research exposes that the memory is growing linearly...

![image](https://user-images.githubusercontent.com/56362817/205114692-fbe368f3-7407-4847-b2c9-479768af2798.png)

actually 500 msg/s work perfectly fine!
600 sometimes but not for long!

@frederikaalund any ideas about that?

**Comment by frederikaalund** [comment]
Hi Andreas, thanks for opening this issue. 👍 Let me have a look.

Great to see a full code example and detailed logs and stats. :)

Your code itself looks good to me. Nothing crazy going on and, as you point out yourself, it simply runs without doing much (the `continue` within the loop).

> `created at /usr/local/lib/python3.8/asyncio/events.py:81> took 4.561 seconds`

All these messages strongly indicate that the event loop is getting bogged down. At 1000 msg/s, there are simply too many tasks to handle at the same time. When this happens, asyncio-mqtt queues them up internally (default `queue_maxsize=0` means infinite queue size). In turn, you see the memory usage go up until the system is out of memory (thanks for providin the performance graph).

When you reduce the frequency to 500-600 msg/s, the system keeps up an everything works.

My take is that you're simply hitting the limits of your system. asyncio-mqtt focuses on correctness and maintainability and *not* performance (most python stuff has the same focus as asyncio-mqtt). If you want performance, I'd argue that you should look at a compiled language (e.g., rust or C++) and their MQTT ecosystem. Can't have it all (correctness, maintainability, and performance), I'm afraid. :)
You could also try to use "raw" paho-mqtt and see if that works better for you. Another alternative is to try out asyncio-mqtt on the same hardware but with another OS (e.g., Ubuntu). It uses a different event loop under the hood (may or may not be better for your use case). On Windows (looks like your system from the screenshots), we use the non-default `SelectorEventLoop` (default is `ProactorEventLoop` but it doesn't work for us because it doesn't have the `add_reader` method). Maybe that hurts performance as well.

In any case, I'd be interested in the performance statistics of different configurations if you're up for it! 
I also welcome any PRs that improve performance if it doesn't cost *too* much in terms of maintainability. 👍 

Hope that this helps you understand the issue better.

~Frederik

**Comment by frederikaalund** [comment]
Forgot to mention that on non-Windows systems you can use the *very fast* [`uvloop`](https://pypi.org/project/uvloop/) as the event loop. That should definitely give you a performance bump as well!

**Comment by empicano** [comment]
Interesting issue and responses! 👍

Following the ideas for more performance, another option is spread the load on multiple machines using [shared subscriptions](https://www.hivemq.com/blog/mqtt5-essentials-part7-shared-subscriptions/) introduced in MQTTv5.

**Comment by AndreasHeine** [comment]
@frederikaalund thanks for the long answer! does `queue_maxsize=10` for example can create backpressure to the broker? for me this would be ideal!
currently i like to figure out what a single python client can do before i start switching the language. maybe scaling instances is enought without rewriting code!

@empican shared Subscription's could be an option but i need to know the limit first and it does not always fit in my case...

**Comment by frederikaalund** [comment]
Glad it helped. 👍 

>  does queue_maxsize=10 for example can create backpressure to the broker? for me this would be ideal!

No, unfortunately, the `queue_maxsize` is a poor man's implementation of "backpressure" (it's not actually backpressure). It is entirely a client-side mechanism (the broker doesn't know about the value of `queue_maxsize`). In turn, if the client is overwhelmed, it simply **drops messages that doesn't fit within the current queue**. A very poor "backpressure" implementation indeed. 😅 Sorry about that.

---

The MQTT specification actually *has* a mechanism for backpressure: [Flow control](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Flow_Control). HiveMQT has [an excellent article about flow control](https://www.hivemq.com/blog/mqtt5-essentials-part12-flow-control/).

At this point in time, however, asyncio-mqtt does not implement flow control. It *is* a feature of the underlying paho-mqtt library (see [max_inflight_messages_set](https://github.com/eclipse/paho.mqtt.python#max_inflight_messages_set)). Currently, we (asyncio-mqtt) do not expose this option but that would be an easy PR (if you're up for it).

The real solution is to rework `queue_maxsize` so that it works together with flow control (so that we don't drop messages). That's probably a breaking change (though I haven't looked into it). Again, PRs are welcome! 😄

**Comment by frederikaalund** [comment]
I also just realized that paho-mqtt's `max_inflight_messages` defaults to `20`. That could explain certainly explain why you don't get a higher throughput than ~500 msg/s.

You could try this hack to see if it helps:

```python
client = Client("test.mosquitto.org")
client._client.max_inflight_messages_set(1000)  # HACK: We access a private member
async with client:
    # Proceed as usual
```

Note that `max_inflight_messages` only kicks in for messages with `qos>0`. Alternatively, try to set `qos=0` on your messages.

**Comment by AndreasHeine** [comment]
let me test that!

**Comment by frederikaalund** [comment]
I think that it's also worth to test `ProtocolVersion.V311` just to see if client/broker (or combination thereof) behaves differently. There were *a lot* of additions in V5 that may change the performance that you see.
