### ISSUE TITLE
Disconnected during message iteration

### ISSUE THREAD

**Issue by vitalerter** [sbtinstruments/asyncio-mqtt#20]
Hi,

I have this issue:

```
ERROR 2020-10-06 08:59:45,391 client 17392 19700 failed to receive on socket: [SSL] malloc failure (_ssl.c:2607)
ERROR 2020-10-06 08:59:45,395 fw_mqtt_client 17392 19700 Broker: <broker> not connected:Disconnected during message iteration
```

Any idea?

Thanks

**Comment by frederikaalund** [comment]
Thanks for raising this issue. Let me have a look.

> [SSL] malloc failure (_ssl.c:2607)

This issue comes from OpenSSL and not from asyncio-mqtt. 

I can see that other people experienced similar issues in the past:
 * https://github.com/locustio/locust/issues/1107
 * https://github.com/openssl/openssl/issues/10015

Please open an issue in the [OpenSSL project](https://github.com/openssl/openssl) instead. Make sure to include your version of OpenSSL and what you did to make the error occur (code samples are always nice).

I'm closing this for now.
