### ISSUE TITLE
Question about publish

### ISSUE THREAD

**Issue by hidaris** [sbtinstruments/asyncio-mqtt#24]
Thanks for the work on this library, I'm using this library and want to publish a message outside of AsyncExitStack but don't know how to do it, any suggestions?

**Comment by frederikaalund** [comment]
Hi hidaris. :) Can you show me what you have tried so far?

**Comment by hidaris** [comment]
@frederikaalund Just like I do [here](https://github.com/hidaris/thingtalk/blob/master/thingtalk/domains/mqtt.py#L76), I'm trying to transform the readme's advance example into a class and can use this instance to publish messages in other contexts, but I don't know if that's what you're suggesting to do.

**Comment by frederikaalund** [comment]
Thanks for adding a some context. I guess that this issue is more about how to use Python's `async with` statements and not so much about asyncio-mqtt itself. I'm afraid that I only offer support for the latter.

Let me make a small exception in this case though. :) Try to turn your `Mqtt` class into an [async context manager](https://www.python.org/dev/peps/pep-0492/#asynchronous-context-managers-and-async-with). That is, add an `__aenter__` and `__aexit__` function to your `Mqtt` class. In turn, you use it as follows:

```python
async with Mqtt(...) as mqtt:
    await mqtt.publish(...)
    # and so on
```
It's up to you to figure out how to convert the advanced example into your new `Mqtt` async context manager. Hint: try to make the `AsyncExitStack` a member of your `Mqtt` class.

In any case, I'm afraid that's all the help that I'll give in this case since it's more about how to use Python in general. Let me know if you have issues with asyncio-mqtt itself. :)

**Comment by frederikaalund** [comment]
Try stackoverflow.com or similar for these general inquiries. :+1:

**Comment by hidaris** [comment]
I will try, thanks for the patient response
