### ISSUE TITLE
Incorrect use of typing.Union

### ISSUE THREAD

**Issue by Equidamoid** [sbtinstruments/asyncio-mqtt#47]
in types.py:
```
ProtocolType = Union[paho.MQTTv31, paho.MQTTv311, paho.MQTTv5]
```
gives 
```
TypeError: Union[arg, ...]: each arg must be a type. Got 3.
```
Reproduces at least on python 3.6, 3.7 & 3.8.

**Comment by frederikaalund** [comment]
Hi there. Thanks for opening this issue. Let me have a look. :)

You're completely right. :+1:  I personally vote for a solution like the following:

```python
class ProtocolVersion(Enum):
    V31 = paho.MQTTv31
    V311 = paho.MQTTv311
    V5 = paho.MQTTv5
```

In turn, we replace `ProtocolType` with `ProtocolVersion`.

I'd like some input from @flyte on this. :)

**Comment by flyte** [comment]
Yeah, you're right indeed. I was imagining that the literal values would be used, so it'd end up being:

```python
typing.Union[typing.Literal[3], typing.Literal[4], typing.Literal[5]]
```

but that's not the case.

I agree with @frederikaalund. The Enum is the way to go. The only question now is where to put it? In types.py, client.py or a new file?

**Comment by frederikaalund** [comment]
I think `ProtocolVersion` would fit nicely into `client.py`. :)

**Comment by frederikaalund** [comment]
Thanks for the fast fix. :) One minor comment:
```python
self._client: mqtt.Client = mqtt.Client(
    client_id=client_id,
    protocol=protocol.value,  # Note the .value part
    clean_session=clean_session,
    transport=transport,
)
```

With that in place, it should work as expected. :+1: Semver-wise, it is a breaking change since users now have to use our `ProtocolVersion` enum instead of a simple `int`. I think that's for the better. :)

**Comment by flyte** [comment]
Oops, yes I was a little hasty with that one. I've gone one-better though, and changed `ProtocolVersion` to an `IntEnum` so that it doesn't actually change the API at all. Users can supply an int, or a `ProtocolVersion`, although for the purposes of documentation (protocol arg isn't actually documented yet) and type hints, we'll stick with `ProtocolVersion`.

```
In [5]: asyncio_mqtt.client.ProtocolVersion.V5 == paho.MQTTv5
Out[5]: True

In [6]: asyncio_mqtt.client.ProtocolVersion.V31 == paho.MQTTv31
Out[6]: True

In [7]: asyncio_mqtt.client.ProtocolVersion.V311 == paho.MQTTv311
Out[7]: True
```

**Comment by frederikaalund** [comment]
Good idea with the `IntEnum`. :) That'll do it!

~Frederik

**Comment by stevemac00** [comment]
I see this is very old issue. I read above protocol could be an int.
This works: `Client(hostname='127.0.0.1', protocol=ProtocolVersion(4))`
This errors: `Client(hostname='127.0.0.1', protocol=4)`
The reason I ask why is because I prefer to pass the client parameters from json config file like: `Client(**conn)`
Where conn is something like: `{"hostname": "10.0.2.116", "transport": "tcp"}`
Am I missing something intuitively obvious to others?
