### ISSUE TITLE
[Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by vitalerter** [sbtinstruments/asyncio-mqtt#62]
I received a lot of disconnections from few servers with same error:
**here is a extra data:** 

- "message": "failed to receive on socket: [Errno 104] Connection reset by peer",
- "path": "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py",

**Comment by frederikaalund** [comment]
Thanks for this issue report. Let me have a look. :)

Sounds like a network issue. From the error message alone, I'm not convinced that this is an asyncio-mqtt-specific issue. I think. Do you have some code that reproduces the issue?

**Comment by vitalerter** [comment]
No, i can't reproduce it, but it happens once for few days. also i looked for rabbitmq broker and get a lot of 
**MQTT: a socket write failed, the socket might already be closed**

**Comment by frederikaalund** [comment]
Thanks for the feedback. :+1: 

> a socket write failed, the socket might already be closed

This is a very general error. It could originate from anywhere in the communication chain. E.g.:
 * Hardware failure
 * Server-side bugs
 * Problems with your network driver

Unless you can pin the issue to something specific in asyncio-mqtt, there is really not much that we (the asyncio-mqtt maintainers) can do about it. Sorry about that.

My suggestions for your next steps:
 * Try with a local setup. Everything (server and client) on a single machine.
 * Try with a different MQTT server
 * Try with a different MQTT client

Those are general suggestions, I know. That's because the error that you see is very general.

**Comment by vitalerter** [comment]
Also i run locally the client and looked at logs and get:

- **[WinError 10054] An existing connection was forcibly closed by the remote host**
- **[code:4] Could not publish message**
- **MqttError('Disconnected during message iteration')**

**Comment by frederikaalund** [comment]
Thanks for the effort. :+1: 

Still, without:

 1. Anything that ties this issue directly to asyncio-mqtt, or,
 2. A code example that reliably reproduces the issue

I can't justify to spend time on it. Sorry about that.

If you manage to produce either 1 or 2, I'll be happy to look into it. Before that, I (as an asyncio-mqtt maintainer) don't have the resources for a bug hunt that might turn out to not be asyncio-mqtt related.
